"""empty message

Revision ID: d68bcd053fd2
Revises: 3d5ba786121c
Create Date: 2024-11-16 00:12:20.856715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68bcd053fd2'
down_revision = '3d5ba786121c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bike', sa.Enum('santaCruz', 'scNomad4Arena', 'kona', 'orbeaRallon', 'summun21', 'cannondaleJekyll2', 'trekSession', 'V102017', 'comSupV5', 'customBike', name='bikes'), nullable=False))
        batch_op.add_column(sa.Column('helmet', sa.Enum('scott', 'troyLeeStage', 'bluegrassLegitIris', 'bluegrassLegit', 'rampage', 'rampagePro', 'rampageCustomIbai', 'pocCoron', 'cienStatus', 'customHelmet', name='helmets'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('helmet')
        batch_op.drop_column('bike')

    # ### end Alembic commands ###
